name             'jhdc-nameserver'
maintainer       'Jeff Hutchison'
maintainer_email 'jeff@jeffhutchison.com'
license          'All rights reserved'
description      'Installs/Configures caching bind server'
long_description 'Installs/Configures caching bind server'
version          '0.3.2'
supports         'centos'
