name             'jhdc-nameserver'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures caching bind server'
long_description 'Installs/Configures caching bind server'
version          '0.3.1'
supports         'centos'
